export {
  STAFF_CATEGORIES,
  STAFF_EMPLOYMENT_TYPES,
  STAFF_GENDERS,
  STAFF_SHIFTS,
  STAFF_STATUSES,
  STAFF_WEEKLY_OFFS,
  dutyDurationLabel,
  inputClass,
  photoSrc,
  staffAddPath,
  staffArchivePath,
  staffInitials,
  staffProfilePath,
  validateStaffForm,
} from './staffConstants.js'

export function emptyStaffForm() {
  return {
    profilePhoto: '',
    fullName: '',
    gender: 'Male',
    dateOfBirth: '',
    fatherOrHusbandName: '',
    mobile: '',
    alternateMobile: '',
    email: '',
    address: '',
    city: '',
    state: '',
    pincode: '',
    staffId: '',
    designation: '',
    designationId: '',
    department: '',
    departmentId: '',
    staffCategory: 'Administration',
    staffCategoryId: '',
    employmentType: 'Full Time',
    joiningDate: new Date().toISOString().slice(0, 10),
    reportingTo: '',
    shift: 'Full Day',
    shiftId: '',
    dutyStart: '09:30',
    dutyEnd: '17:30',
    weeklyOff: 'Sunday',
    qualification: '',
    experienceYears: '',
    monthlySalary: '',
    emergencyName: '',
    emergencyRelation: '',
    emergencyPhone: '',
    notes: '',
    status: 'Active',
  }
}

export function staffToForm(entry) {
  const personal = entry?.personalDetails || {}
  const employment = entry?.employmentDetails || {}
  const emergency = entry?.emergencyContact || {}
  return {
    ...emptyStaffForm(),
    profilePhoto: personal.profilePhoto || entry?.profilePhoto || '',
    fullName: personal.fullName || entry?.fullName || '',
    gender: personal.gender || entry?.gender || 'Male',
    dateOfBirth: personal.dateOfBirth || '',
    fatherOrHusbandName: personal.fatherOrHusbandName || '',
    mobile: personal.mobile || entry?.mobile || '',
    alternateMobile: personal.alternateMobile || '',
    email: personal.email || entry?.email || '',
    address: personal.address || '',
    city: personal.city || '',
    state: personal.state || '',
    pincode: personal.pincode || '',
    staffId: entry?.staffId || '',
    designation: employment.designation || entry?.designation || '',
    designationId: employment.designationId || '',
    department: employment.department || entry?.department || '',
    departmentId: employment.departmentId || '',
    staffCategory: employment.staffCategory || entry?.staffCategory || 'Administration',
    staffCategoryId: employment.staffCategoryId || '',
    shift: employment.shift || entry?.shift || 'Full Day',
    shiftId: employment.shiftId || '',
    dutyStart: employment.dutyStart || entry?.dutyStart || '',
    dutyEnd: employment.dutyEnd || entry?.dutyEnd || '',
    weeklyOff: employment.weeklyOff || entry?.weeklyOff || 'Sunday',
    reportingTo: employment.reportingTo || entry?.reportingTo || '',
    qualification: employment.qualification || '',
    experienceYears: employment.experienceYears ?? '',
    joiningDate: employment.joiningDate || entry?.joiningDate || '',
    employmentType: employment.employmentType || 'Full Time',
    monthlySalary: employment.monthlySalary || entry?.monthlySalary || '',
    emergencyName: emergency.name || entry?.emergencyName || '',
    emergencyRelation: emergency.relation || '',
    emergencyPhone: emergency.phone || entry?.emergencyPhone || '',
    notes: entry?.notes || '',
    status: entry?.status || 'Active',
  }
}

export function formToPayload(form) {
  return {
    personalDetails: {
      fullName: form.fullName,
      profilePhoto: form.profilePhoto,
      gender: form.gender,
      dateOfBirth: form.dateOfBirth || null,
      fatherOrHusbandName: form.fatherOrHusbandName,
      mobile: form.mobile,
      alternateMobile: form.alternateMobile,
      email: form.email,
      address: form.address,
      city: form.city,
      state: form.state,
      pincode: form.pincode,
    },
    employmentDetails: {
      designation: form.designation,
      designationId: form.designationId,
      department: form.department,
      departmentId: form.departmentId,
      staffCategory: form.staffCategory,
      staffCategoryId: form.staffCategoryId,
      shift: form.shift,
      shiftId: form.shiftId,
      dutyStart: form.dutyStart,
      dutyEnd: form.dutyEnd,
      weeklyOff: form.weeklyOff,
      reportingTo: form.reportingTo,
      qualification: form.qualification,
      experienceYears: Number(form.experienceYears) || 0,
      joiningDate: form.joiningDate || null,
      employmentType: form.employmentType,
      monthlySalary: Number(form.monthlySalary) || 0,
    },
    emergencyContact: {
      name: form.emergencyName,
      relation: form.emergencyRelation,
      phone: form.emergencyPhone,
    },
    notes: form.notes,
    status: form.status,
  }
}
